### PR TITLE
Optimize layout for embedding

### PR DESCRIPTION
**Pull request by poikilotherm**
Currently the embedded version of DataverseTV at https://dataverse.org/dataversetv is suboptimal.

image

Let's make that better...

### CODE REVIEW

**Comment by poikilotherm** [comment]
Here's how this looks like with the test pages:

image

image

**Comment by pdurbin** [comment]
Merged! Let's give it a try! Thanks, @poikilotherm!

**Comment by pdurbin** [comment]
Here's before and after at https://dataverse.org/dataversetv now that this PR has been deployed:

## before

Screenshot 2023-06-13 at 8 11 37 AM


## after

Screenshot 2023-06-13 at 8 13 02 AM

**Comment by poikilotherm** [comment]
I like!

image

**Comment by pdurbin** [comment]
One side effect is that while I used to be able to see two videos at once side by side on mobile, now I can only see one:

Screenshot_20230613-082008

**Comment by poikilotherm** [comment]
Oh I thought you wanted it this way! Because you're having "width=300px" in it. Let me get the CSS right for this.

**Comment by pdurbin** [comment]
I could be misremembering how it looked on mobile. 😅 

It's fine this way.

**Comment by poikilotherm** [comment]
Not sure it would be worth it.

image

**Pull request merged**
