### PR TITLE
new design #1

### PR DESCRIPTION
**Pull request by erikbuunk**
updated css, html and added svg image

image

I hope you like it.

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
The changes look good (I can reformat the HTML later with the script in "util"). I tested it locally and it looks great! Thanks, @erikbuunk 🎉 🎉 😄 

Here's a screenshot from my laptop (I didn't test it on a phone):

Screen Shot 2020-02-27 at 2 51 47 PM

**Comment by pdurbin** [comment]
@TaniaSchlatter @mheppler @djbrooke I moved this to QA but you are welcome to take a look! Merging this pull request will update the iframe at https://dataverse.org/dataversetv (and the fonts should match now).

**Comment by kcondon** [comment]
@pdurbin Not sure whether I should be getting this in QA, plus I have no perm to merge/assign in this repo

**Comment by djbrooke** [comment]
I'll take it for now, thanks!

**Comment by poikilotherm** [comment]
This indeed does look very good and promising! Great work @erikbuunk, I like it :smile:

**Comment by michbarsinai** [comment]
Very nice work. Thanks, @erikbuunk!

**Comment by metasj** [comment]
I like this a lot :)  However it does add a fair bit of whitespace, and I really liked the density of the old format.  Thoughts: 
~ Reduce whitespace between the bottom of the video and the title
~ Move the 'Slides' link to the same line / just below the title, to save another linebreak
~ Reduce whitespace padding at the very bottom by a half-line: the grey border allows less whitespace [else drop the border + shadow]

**Comment by erikbuunk** [comment]
@metasj 

Normally I like whitespace, but I agree with your suggestions 😄 
> I like this a lot :) However it does add a fair bit of whitespace, and I really liked the density of the old format. Thoughts:
> ~ Reduce whitespace between the bottom of the video and the title
> ~ Move the 'Slides' link to the same line / just below the title, to save another linebreak
> ~ Reduce whitespace padding at the very bottom by a half-line: the grey border allows less whitespace [else drop the border + shadow]

How about this:
image


I also found a bug in the slide links (it was shown on every card). This will be fixed.

**Comment by erikbuunk** [comment]
@pdurbin Tomorrow a year that we have opened this item! Curious about the next steps of this improvement :)

**Comment by pdurbin** [comment]
@erikbuunk I'm not sure but I still think it's a huge improvement!

**Review by atrisovic — APPROVED** [review]
LGTM!

**Pull request merged**
